spring:
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  application:
  name: sblearn-redis
  boot:
    admin:
      client:
        url: http://localhost:8000
management:
  endpoints:
    web:
      exposure:
        include: trace,beans,health,info,headdump,threaddump
server:
  port: 8002