spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?characterEncoding=utf-8
    username: jpa
    password: jpa123
    driver-class-name: com.mysql.cj.jdbc.Driver