spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/task?characterEncoding=utf-8
    username: task
    password: task123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: sblearn-task
  boot:
    admin:
      client:
        url: http://localhost:8000
management:
  endpoints:
    web:
      exposure:
        include: trace,beans,health,info,headdump,threaddump
server:
  port: 8001